version: '3'
services:
  backend:
    build:
      context: ./packages/notification-test-backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mongo
  frontend:
    build:
      context: ./packages/notification-test-front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db