version: '3'
services:
  backend:
    build:
      # context: ./packages/notification-test-backend
      # dockerfile: Dockerfile
      dockerfile: backend.dockerfile
    ports:
      - '3001:3001'
    command: sh -c "sleep 10 && npm run data-seed && npm run start:prod"
    depends_on:
      - mongo
  frontend:
    build:
      # context: ./packages/notification-test-front
      # dockerfile: Dockerfile
      dockerfile: frontend.dockerfile
    ports:
      - '3000:3000'
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db